[project]
name = "evidently-repo-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "evidently>=0.7.3",
    "ipykernel>=6.29.5",
]
